Qshop/Buyer/urls.py
from django.urls import path,re_path
from Buyer.views import *
from django.views.decorators.cache import cache_page

urlpatterns = [
    path("login/",login),
    path("index/",index),
    path("register/",register),
    path("logout/",logout),
    # path("goods_list/",cache_page(60*15)(goods_list)),
    path("goods_list/",goods_list),
    path("user_center_info/",user_center_info),
    path("place_order/",place_order),
    path("alipayviews/",AlipayViews),
    path("payresult/",payresult),
    path("add_cart/",add_cart),
    path("cart/",cart),
    path("cache_test/",cache_test),
    path("reqtest/",reqtest),
    path("user_center_site/",user_center_site),
    path("myporcess_tem_rep/",myporcess_tem_rep),
    path("place_order_more/",place_order_more),
    path("user_center_order/",user_center_order),
    re_path("detail/(?P<id>\d+)",detail),

    ###  path("Saller/",include("Saller.urls")),
]

Qshop/Qshop/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from Buyer.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("Saller/",include("Saller.urls")),
    path("Buyer/",include("Buyer.urls")),
    re_path("^$",index),

]

Qshop/Saller/urls.py
from django.urls import path,re_path
from Saller.views import *

urlpatterns = [
    path('register/',register),
    path('login/',login),
    path('index/',index),
    path('logout/',logout),
    path('goods_list/',goods_list),
    re_path('goods_list/(?P<status>[01])/(?P<page>\d+)',goods_list),
    re_path('goods_status/(?P<status>\w+)/(?P<id>\d+)',goods_status),
    path('personal_info/',personal_info),
    path('goods_add/',goods_add),
    path('get_code/',get_code),
    path('seller_caozuo/',seller_caozuo),
    re_path('order/(?P<status>\d{1})',order),
]

Qshop/Buyer/models.py
from django.db import models
from Saller.models import *

# Create your models here.


ORDER_STATUS = (
    (0,"未支付"),
    (1,"已支付"),
    (2,"待发货"),
    (3,"待收货"),
    (4,"完成"),
    (5,"拒收"),
)

## 订单表
class PayOrder(models.Model):
    ###订单状态：
    # 0 未支付
    # 1 已支付
    # 2  待发货
    # 3  待收货
    # 4   完成
    # 5   拒收
    order_number = models.CharField(max_length=32,verbose_name="订单编号",unique=True)
    order_date = models.DateField(auto_now=True,verbose_name="订单日期")
    order_status = models.IntegerField(choices=ORDER_STATUS,verbose_name="订单状态")
    order_total = models.FloatField(verbose_name="订单总价")
    order_user = models.ForeignKey(to= LoginUser,on_delete=models.CASCADE,verbose_name="订单用户")## 外键  链接到  用户表




ORDERINFO_STATUS = (
    (0,"未支付"),
    (1,"已支付"),
    (2,"已发货"),
    (3,"已完成"),
    (4,"拒绝发货"),
)

## 订单详情表
class OrderInfo(models.Model):
    order_id = models.ForeignKey(to=PayOrder,on_delete=models.CASCADE,verbose_name="订单表外键")
    goods = models.ForeignKey(to=Goods,on_delete=models.CASCADE,verbose_name="商品表")
    goods_price = models.FloatField(verbose_name="商品单价")   #### 指下单的时候，商品的单价
    goods_count = models.IntegerField(verbose_name="商品数量")
    goods_total_price = models.FloatField(verbose_name="商品小计")
    store_id = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE,verbose_name="店铺id")
    status = models.IntegerField(choices=ORDERINFO_STATUS,default=0)

class Cart(models.Model):

    goods_number = models.IntegerField(verbose_name="商品数量")
    goods_price = models.FloatField(verbose_name="商品单价")
    goods_total = models.FloatField(verbose_name="商品总价")
    goods = models.ForeignKey(to=Goods,on_delete=models.CASCADE)
    cart_user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE)
    order_number = models.CharField(max_length=32,default=0)


class UserAdress(models.Model):
    user_name = models.CharField(max_length=32)
    user_address = models.TextField()
    user_code = models.CharField(max_length=32)
    user_phone = models.CharField(max_length=11)
    status = models.IntegerField(default=0)
    user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE)

Qshop/Saller/models.py
from django.db import models
from django.db.models import Manager

# Create your models here.
class LoginUser(models.Model):
    ## id 不需要写
    email = models.EmailField()
    password = models.CharField(max_length=32)
    username = models.CharField(max_length=32,null=True,blank=True)
    phone_number = models.CharField(max_length=11,null=True,blank=True)
    photo = models.ImageField(upload_to="images",null=True,blank=True)   ## /static/images
    age = models.IntegerField(null=True,blank=True)
    gender = models.CharField(null=True,blank=True,max_length=4)
    address = models.TextField(null=True,blank=True)
    ### 0 代表的卖家 1 代表买家 2 管理员
    user_type = models.IntegerField(default=1)

    ###  null 针对数据库，表示可以为空，即在数据库的存储中可以为空
    ### blank 针对表单，表示在表单中该字段可以不填，但是对数据库没有影响



class MyGoodsType(Manager):
    def myaddtype(self,type_label,type_description,type_picture="images/banner01.jpg"):
        goods_type = GoodsType()
        goods_type.type_label = type_label
        goods_type.type_description = type_description
        goods_type.type_picture = type_picture
        goods_type.save()

        return goods_type




### 类型模型
class GoodsType(models.Model):
    type_label = models.CharField(max_length=32)
    type_description = models.TextField()
    type_picture = models.ImageField(upload_to="images")
    objects = MyGoodsType()

class MyGoodsFilter(Manager):
    ##自定义方法
    ## 自定义查询    查询条件： id < 10 的商品
    def myfilter(self):
        data = Goods.objects.filter(id__lt = 10).values("goods_name")
        return data


class Goods(models.Model):
    goods_number = models.CharField(max_length=11,verbose_name="商品编号")
    goods_name = models.CharField(max_length=32,verbose_name="商品的名字")
    goods_price = models.FloatField(verbose_name="价格")
    goods_count = models.IntegerField(verbose_name="数量")
    goods_location = models.CharField(max_length=254,verbose_name="产地")
    goods_safe_date = models.IntegerField(verbose_name="保质期")
    goods_status = models.IntegerField(verbose_name="状态")  ## 0 代表下架  1 代表在售
    goods_pro_time = models.DateField(auto_now=True,verbose_name="生产日期")
    picture = models.ImageField(upload_to="images")   ## 商品图片
    goods_description = models.TextField(default="好好。。。。。")
    ## 类型  一对多
    goods_type = models.ForeignKey(to=GoodsType,on_delete=models.CASCADE,default=1)
    ## 店铺 一对多
    goods_store = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE,default=1)

    objects = MyGoodsFilter()


class Vaild_Code(models.Model):
    code_content = models.CharField(max_length=8,verbose_name="验证码")
    code_time = models.CharField(max_length=32,verbose_name="创建时间")
    code_status = models.IntegerField(verbose_name="状态")    ##1 使用  0 未使用
    code_user = models.EmailField(verbose_name="邮箱")

Qshop/Saller/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from Saller.models import *
import hashlib
from django.core.paginator import Paginator
# Create your views here.

## 登录装饰器
def LoginVaild(func):
    ## 1. 获取cookie中username和email
    ## 2. 判断username和email
    ## 3. 如果成功  跳转
    ## 4. 如果失败   login.html
    def inner(request,*args,**kwargs):
        username = request.COOKIES.get('username')
        ## 获取session
        session_username = request.session.get("username")
        if username and session_username and username == session_username:
            return func(request,*args,**kwargs)
        else:
            return HttpResponseRedirect('/Saller/login/')
    return inner

## 密码加密
def setPassword(password):
    md5 = hashlib.md5()
    md5.update(password.encode())
    result = md5.hexdigest()
    return result

## 注册
def register(request):
    if request.method == "POST":
        error_msg = ""
        email = request.POST.get("email")
        password = request.POST.get("password")
        if email:
            ## 判断邮箱是否存在
            loginuser = LoginUser.objects.filter(email=email).first()
            if not loginuser:
                ## 不存在 写库
                user = LoginUser()
                user.email = email
                user.username = email
                user.password = setPassword(password)
                user.user_type = 0
                user.save()
            else:
                error_msg = "邮箱已经被注册，请登录"
        else:
            error_msg = "邮箱不可以为空"

    return render(request,"saller/register.html",locals())

## 登录
import datetime
import time
def login(request):
    if request.method == "POST":
        error_msg = ""
        email = request.POST.get("email")
        password = request.POST.get("password")
        code = request.POST.get("vaild_code")
        if email:
            user = LoginUser.objects.filter(email=email,user_type=0).first()
            if user:
                ## 存在
                if user.password == setPassword(password):
                    ## 登录成功
                    ## 跳转页面
                    # error_msg = "登录成功"
                    # return HttpResponseRedirect('/index/')
                    ## 设置cookie

                    ## 判断验证码   从库里取验证码
                    vaild_code = Vaild_Code.objects.filter(code_status=0,code_user=email,code_content=code).first()
                    ## 判断时间  有效期2分钟  当前时间 - code创建时间 <= 2min
                    # now = time.time()
                    now = time.mktime(datetime.datetime.now().timetuple())
                    db_time = datetime.datetime.strptime(vaild_code.code_time, "%Y-%m-%d %H:%M:%S")
                    db_time = time.mktime(db_time.timetuple())
                    #
                    if (now - db_time)/ 60 > 2:
                        ## 超时
                        error_msg = "验证码超时"
                    else:
                        response  = HttpResponseRedirect("/Saller/index/")
                        response.set_cookie("username",user.username)
                        response.set_cookie("userid",user.id)
                        request.session['username'] = user.username  ## 设置session
                        vaild_code.code_status = 1
                        vaild_code.save()
                        return response
                else:
                    error_msg = "密码错误"
            else:
                error_msg = "用户不存在"
        else:
            error_msg = "邮箱不可以为空"
    return render(request,"saller/login.html",locals())
import calendar
import datetime
def get_day():
    """
    获取每月的第一天和最后一天的日期
    :return:   date
    """
    now = datetime.datetime.now()
    year = now.year
    month = now.month
    last_day = calendar.monthrange(year, month)[1]  ## 最后一天
    start = datetime.date(year, month, 1)
    end = datetime.date(year, month, last_day)
    return start,end



from django.db.models import *
## 首页
@LoginVaild
def index(request):
    user_id = request.COOKIES.get("userid")    ###获取卖家id
    ## 查询订单详情
    # order_info = OrderInfo.objects.filter(store_id=LoginUser.objects.get(id = user_id)).all()
    ##当月成交额
    ##   获取当前月份
    ##   查询当前月份下的订单详情
          ### 日期 在订单表中，跟订单详情表是 一对多关系
    ### 首先获取当前年    当前月    当前天   获取当前月的最后一天
    ## 拼接（string) -> date
    start,end = get_day()
    payorder = PayOrder.objects.filter(order_date__range = [start,end])   ## 当前日期下面所有的订单
    # print (payorder)
    order_info = OrderInfo.objects.filter(store_id = LoginUser.objects.get(id = user_id),order_id__in=payorder).exclude(status__in=[0,4])
    ## 聚合
    sum_all = order_info.aggregate(Sum("goods_total_price"),Count("id"),Sum("goods_count"))
    print(sum_all)

    sum_money = sum_all.get("goods_total_price__sum")
    sum_count = sum_all.get("id__count")
    sum_goods_count = sum_all.get("goods_count__sum")

    if sum_money is None:
        sum_money=0


    ## 返回当月销量最高的单品
    # result = {}
    # for one in order_info:
    #     goods_info = one.goods  ##正向查询
    #     goods_id = goods_info.id
    #     if goods_id in result.keys():
    #         result[goods_id] += one.goods_count
    #     else:
    #         result[goods_id] = one.goods_count
    #
    # result = max(result, key=lambda x: result[x])
    # result = Goods.objects.get(id=result)
    # result = result.goods_name
    data = OrderInfo.objects.exclude(status__in=[0,4]).values("goods").annotate(goods_num=Sum("goods_count")).order_by("-goods_num").first()
    result = data.get("goods")   ## goods_id
    result = Goods.objects.get(id=result)
    result = result.goods_name


        # .values("goods_num")

    return render(request,"saller/index.html",locals())

## 登出
def logout(request):
    # 删除cookie   删除  session
    response = HttpResponseRedirect("/Saller/login/")
    # response.delete_cookie("kename")
    keys = request.COOKIES.keys()
    for one in keys:
        response.delete_cookie(one)

    del request.session['username']
    return response
## 商品列表
def goods_list(request,status,page=1):
    """

    :param request:
    :param status: 想要获取的是 在售或者下架的商品   在售传参1   下架是 0
    :param page:   页
    :return:
    """
    page = int(page)
    if status == "0":
        ## 下架商品
        goods_obj = Goods.objects.filter(goods_status = 0).order_by('goods_number')
    else:
        ## 在售商品
        goods_obj = Goods.objects.filter(goods_status = 1).order_by('goods_number')
    goods_all = Paginator(goods_obj,10)
    goods_list = goods_all.page(page)  ##

    return render(request,"saller/goods_list.html",locals())


## 商品状态
def goods_status(request,status,id):
    """
    完成当 下架  修改 status 为 0
    当 上架的   修改status 为 1
    :param request:
    :param status:  操作内容  up 上架    down   下架
     :param id:  商品id
    :return:
    """
    id = int(id)
    goods = Goods.objects.get(id=id)
    if status== "up":
        ###上架
        goods.goods_status = 1
    else:
        ## 下架
        goods.goods_status = 0
    goods.save()
    # return HttpResponseRedirect("/goods_list/1/1/")
    ##  获取请求来源
    url =request.META.get("HTTP_REFERER","/Saller/goods_list/1/1/")
    return HttpResponseRedirect(url)

@LoginVaild
def personal_info(request):
    ##
    user_id = request.COOKIES.get("userid")
    print (user_id)
    user = LoginUser.objects.filter(id = user_id).first()
    if request.method == "POST":
        ## 获取 数据，保存数据
        data = request.POST
        print (data.get("email"))
        user.username = data.get("username")
        user.phone_number = data.get("phone_number")
        user.age = data.get("age")
        user.gender = data.get("gender")
        user.address = data.get("address")
        user.photo = request.FILES.get("photo")
        user.save()
        print (data)
    return render(request,"saller/personal_info.html",locals())

@LoginVaild
def goods_add(request):
    ###  处理post请求，获取数据，保存数据，返回响应
    goods_type = GoodsType.objects.all()
    if request.method == "POST":
        data = request.POST
        print (data)
        goods = Goods()
        goods.goods_number = data.get("goods_number")
        goods.goods_name = data.get("goods_name")
        goods.goods_price = data.get("goods_price")
        goods.goods_count = data.get("goods_count")
        goods.goods_location = data.get("goods_location")
        goods.goods_safe_date = data.get("goods_safe_date")
        goods.picture = request.FILES.get("picture")
        goods.goods_status = 1
        goods.save()
        goods_type_id = request.POST.get("goods_type")   ## select 标签的value  类型是 string
        # goods.goods_type_id = int(goods_type_id)
        goods.goods_type = GoodsType.objects.get(id = goods_type_id)  ## 保存类型
        ## 保存店铺
        ## 从cookie中获取到用户信息
        user_id = request.COOKIES.get("userid")
        goods.goods_store = LoginUser.objects.get(id = user_id)
        goods.save()
    return render(request,"saller/goods_add.html",locals())


import smtplib
from email.mime.text import MIMEText

def send_email(params):
    ## params   字典类型
    """
    :param params:   字典
        subject  主题
        content  邮件内容
        toemail  收件人 列表
    :return:
    """
    subject = params.get("subject")
    content = params.get("content")
    sender = "str_wjp@163.com"
    rec = params.get("toemail")
    password = "qaz123"
    message = MIMEText(content,"plain","utf-8")
    message["Subject"] = subject
    message["From"] = sender   ## 发件人
    message["To"] = str(rec)   ## 收件人
    try:
        smtp = smtplib.SMTP_SSL("smtp.163.com",465)
        smtp.login(sender,password)
        smtp.sendmail(sender,rec,message.as_string())
        smtp.close()
        return True
    except:
        return False

# import random
# def get_code(request):
#     result = {"code":10000,"msg":""}
#     ## 获取email
#     email = request.GET.get("email")
#     print(email)
#     ##  判断用户是否存在
#     if email:
#         ## 判断  email 是否有值
#         flag = LoginUser.objects.filter(email = email).exists()
#         if flag:
#             ## 用户存在
#             ##发送验证码

Qshop/Saller/templates/saller/goods_add.html
{% extends "saller/base.html" %}
{% block title %}
    增加商品
{% endblock %}

{% block content %}
    <form action="" method="post" class="user" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" name="goods_number" placeholder="商品编号" class="form-control form-control-user">
        </div>
        <div class="form-group">
            <input type="text" name="goods_name" placeholder="商品名字" class="form-control form-control-user">
        </div>
        <div class="form-group">
            <input type="text" name="goods_price" placeholder="商品价格" class="form-control form-control-user">
        </div>
        <div class="form-group">
            <input type="text" name="goods_count" placeholder="商品数量" class="form-control form-control-user">
        </div>
        <div class="form-group">
            <input type="text" name="goods_location" placeholder="商品产地" class="form-control form-control-user">
        </div>
        <div class="form-group">
            <input type="text" name="goods_safe_date" placeholder="商品保质期" class="form-control form-control-user">
        </div>


       <div class="form-group">
{#            <input type="text" name="goods_type" placeholder="商品类型" class="form-control form-control-user">#}
           <select name="goods_type" class="btn btn-warning dropdown-toggle btn-user btn-block">
               <option value="0" >--请选择类型--</option>
               {% for one in goods_type %}
                    <option value="{{ one.id }}" >{{ one.type_label }}</option>
               {% endfor %}
           </select>
        </div>
        <div class="form-group">

           上传图片：<input type="file" name="picture">
        </div>

        <input class="btn btn-primary btn-user btn-block" type="submit" value="增加商品">


</form>
{% endblock%}

Qshop/Saller/templates/saller/goods_list.html
{% extends "saller/base.html" %}
{% block title %}
    商品列表
{% endblock %}

{% block label %}
    商品列表
    <a href="/Saller/goods_add/">增加商品</a>
{% endblock %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th>商品编号</th>
            <th>商品名称</th>
            <th>商品价格</th>
            <th>商品数量</th>
            <th>商品产地</th>
            <th>商品保质期</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for one in goods_list %}
            <tr>
                <td>{{ one.goods_number }}</td>
                <td>{{ one.goods_name }}</td>
                <td>{{ one.goods_price }}</td>
                <td>{{ one.goods_count }}</td>
                <td>{{ one.goods_location }}</td>
                <td>{{ one.goods_safe_date }}</td>
                <td>
                    <button class="btn btn-primary">修改</button>
                    {#                    <button class="btn btn-warning">下架</button>#}
                    {% if one.goods_status == 1 %}
                        <a href="/Saller/goods_status/down/{{ one.id }}" type="button" class="btn btn-warning">下架</a>
                    {% else %}
                        <a href="/Saller/goods_status/up/{{ one.id }}" type="button" class="btn btn-warning">上架</a>

                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot></tfoot>
    </table>

    <ul style="float:right; margin-right: 50px" class="pagination">

        {% for one in goods_all.page_range %}
            <li class="paginate_button page-item previous">
                {#                {% if one.goods_status == 1 %}#}
                {% if status == "1" %}
                    <a href="/goods_list/1/{{ one }}" class="page-link">{{ one }}</a>
                {% else %}
                    <a href="/goods_list/0/{{ one }}" class="page-link">{{ one }}</a>
                {% endif %}
            </li>
        {% endfor %}

    </ul>




{% endblock %}

Qshop/Saller/templates/saller/login.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Register</title>

    <!-- Custom fonts for this template-->
    <link href="/static/saller/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/static/saller/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-5 d-none d-lg-block bg-login-image"></div>
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">登录</h1>
                        </div>
                        <form class="user" method="post">
                            {% csrf_token %}

                            <div class="form-group">
                                <input type="email" name='email' class="form-control form-control-user"
                                       id="exampleInputEmail" placeholder="邮箱">
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-12 mb-3 mb-sm-0">
                                    <input type="password" name="password" class="form-control form-control-user"
                                           id="exampleInputPassword" placeholder="密码">
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-8 mb-3 mb-sm-0">
                                    <input type="text" name="vaild_code" class="form-control form-control-user"
                                           id="exampleInputPassword" placeholder="验证码">
                                </div>
                                <div class="col-sm-4 mb-3 mb-sm-0">
                                    <input type="button"  class="btn btn-google btn-user btn-block"
                                           onclick="get_code()" value="验证码">
                                </div>
                            </div>
                            <input type="submit" value="登录" class="btn btn-primary btn-user btn-block">

                            </input>
                            <hr>
                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small" href="forgot-password.html">忘记密码</a>
                        </div>
                        <div class="text-center">
                            <a class="small" href="/Saller/register/">去注册</a>
                            <p style="color: red">
                                {{ error_msg }}
                            </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- Bootstrap core JavaScript-->
<script src="/static/saller/vendor/jquery/jquery.min.js"></script>
<script src="/static/saller/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="/static/saller/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="/static/saller/js/sb-admin-2.min.js"></script>
<script>
    function get_code() {
        //  ajax   get请求
        //获取邮箱
        var email = $("#exampleInputEmail").val();
        var url = '/Saller/get_code/?email='+email;     //  获取验证码的地址
        $.ajax({
            url:url,
            type:"get",
            data:"",
            success:function (data) {
                console.log(data)
            },
            error:function (error) {
                console.log(error)
            }
        })



    }


</script>

</body>

</html>

Qshop/Saller/templates/saller/order.html
{% extends "saller/base.html" %}
{% block title %}
    订单列表
{% endblock %}

{% block label %}
    订单列表
{% endblock %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th>订单编号</th>
            <th>订单商品</th>
            <th>商品数量</th>
            <th>收货地址</th>
            <th>收货人</th>
            <th>订单总价</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for one in order_info %}
            <tr>
                <td>{{ one.order_id.order_number }}</td>
                <td>{{ one.goods.goods_name }}</td>
                <td>{{ one.goods_count }}</td>
                <td>{{ one.order_id.order_user.useradress_set.first.user_address }}</td>
                <td>{{ one.order_id.order_user.useradress_set.first.user_name }}</td>
                <td>{{ one.goods_total_price }}</td>
                <td>
                    {% if one.status == 0 %}
                        <a href="#" type="button" class="btn btn-warning">提醒支付</a>
                        <a href="/Saller/seller_caozuo/?type=jujue&order_info_id={{ one.id }}" type="button" class="btn btn-warning">拒绝订单</a>
                    {% elif one.status == 1 %}
                        <a href="/Saller/seller_caozuo/?type=fahuo&order_info_id={{ one.id }}" type="button" class="btn btn-warning">立即发货</a>
                     {% elif one.status == 2 %}
                        <a href="#" type="button" class="btn btn-warning">查看物流</a>
                      {% elif one.status == 3 %}
                        <a href="#" type="button" class="btn btn-warning">查看订单详情</a>
                    {% endif %}

                    {#                    <button class="btn btn-warning">下架</button>#}

                </td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot></tfoot>
    </table>

    <ul style="float:right; margin-right: 50px" class="pagination">

        {% for one in goods_all.page_range %}
            <li class="paginate_button page-item previous">
                {#                {% if one.goods_status == 1 %}#}
                {% if status == "1" %}
                    <a href="/goods_list/1/{{ one }}" class="page-link">{{ one }}</a>
                {% else %}
                    <a href="/goods_list/0/{{ one }}" class="page-link">{{ one }}</a>
                {% endif %}
            </li>
        {% endfor %}

    </ul>




{% endblock %}

Qshop/Saller/templates/saller/personal_info.html
{% extends "saller/base.html" %}
{% block title %}
    个人中心
{% endblock %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table">
        <tr>
            <td rowspan="3" style="width: 300px;">
                <img style="width: 300px;height:300px" src="/static/{{ user.photo }}" alt="">
                <input type="file" name="photo">
            </td>
            <th>邮箱</th>
            <td><input type="text" name = "email" value="{{ user.email }}" disabled></td>
            <th>用户名</th>
            <td><input type="text" name = "username" value="{{ user.username }}"></td>
        </tr>
        <tr>
            <th>手机号</th>
            <td><input type="text" name = "phone_number" value="{{ user.phone_number }}"></td>

            <th>年龄</th>
            <td><input type="text" name = "age" value="{{ user.age }}"></td>
        </tr>
        <tr>
            <th>性别</th>
            <td><input type="text" name = "gender" value="{{ user.gender }}"></td>
            <th>地址</th>
            <td><input type="text" name = "address" value="{{ user.address }}"></td>
        </tr>
        <tr>
            <td colspan="5" style="text-align: center">
                <input class = "btn btn-primary "type="submit" value="完善用户信息">
            </td>
        </tr>

    </table>
    </form>

{% endblock %}