Qshop/Buyer/urls.py
from django.urls import path,re_path
from Buyer.views import *
from django.views.decorators.cache import cache_page

urlpatterns = [
    path("login/",login),
    path("index/",index),
    path("register/",register),
    path("logout/",logout),
    # path("goods_list/",cache_page(60*15)(goods_list)),
    path("goods_list/",goods_list),
    path("user_center_info/",user_center_info),
    path("place_order/",place_order),
    path("alipayviews/",AlipayViews),
    path("payresult/",payresult),
    path("add_cart/",add_cart),
    path("cart/",cart),
    path("cache_test/",cache_test),
    path("reqtest/",reqtest),
    path("user_center_site/",user_center_site),
    path("myporcess_tem_rep/",myporcess_tem_rep),
    path("place_order_more/",place_order_more),
    path("user_center_order/",user_center_order),
    re_path("detail/(?P<id>\d+)",detail),

    ###  path("Saller/",include("Saller.urls")),
]

Qshop/Qshop/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from Buyer.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("Saller/",include("Saller.urls")),
    path("Buyer/",include("Buyer.urls")),
    re_path("^$",index),

]

Qshop/Buyer/models.py
from django.db import models
from Saller.models import *

# Create your models here.


ORDER_STATUS = (
    (0,"未支付"),
    (1,"已支付"),
    (2,"待发货"),
    (3,"待收货"),
    (4,"完成"),
    (5,"拒收"),
)

## 订单表
class PayOrder(models.Model):
    ###订单状态：
    # 0 未支付
    # 1 已支付
    # 2  待发货
    # 3  待收货
    # 4   完成
    # 5   拒收
    order_number = models.CharField(max_length=32,verbose_name="订单编号",unique=True)
    order_date = models.DateField(auto_now=True,verbose_name="订单日期")
    order_status = models.IntegerField(choices=ORDER_STATUS,verbose_name="订单状态")
    order_total = models.FloatField(verbose_name="订单总价")
    order_user = models.ForeignKey(to= LoginUser,on_delete=models.CASCADE,verbose_name="订单用户")## 外键  链接到  用户表




ORDERINFO_STATUS = (
    (0,"未支付"),
    (1,"已支付"),
    (2,"已发货"),
    (3,"已完成"),
    (4,"拒绝发货"),
)

## 订单详情表
class OrderInfo(models.Model):
    order_id = models.ForeignKey(to=PayOrder,on_delete=models.CASCADE,verbose_name="订单表外键")
    goods = models.ForeignKey(to=Goods,on_delete=models.CASCADE,verbose_name="商品表")
    goods_price = models.FloatField(verbose_name="商品单价")   #### 指下单的时候，商品的单价
    goods_count = models.IntegerField(verbose_name="商品数量")
    goods_total_price = models.FloatField(verbose_name="商品小计")
    store_id = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE,verbose_name="店铺id")
    status = models.IntegerField(choices=ORDERINFO_STATUS,default=0)

class Cart(models.Model):

    goods_number = models.IntegerField(verbose_name="商品数量")
    goods_price = models.FloatField(verbose_name="商品单价")
    goods_total = models.FloatField(verbose_name="商品总价")
    goods = models.ForeignKey(to=Goods,on_delete=models.CASCADE)
    cart_user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE)
    order_number = models.CharField(max_length=32,default=0)


class UserAdress(models.Model):
    user_name = models.CharField(max_length=32)
    user_address = models.TextField()
    user_code = models.CharField(max_length=32)
    user_phone = models.CharField(max_length=11)
    status = models.IntegerField(default=0)
    user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE)

Qshop/Buyer/views.py
from django.shortcuts import render
from Saller.models import *
from Saller.views import setPassword
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from Buyer.models import *
from alipay import AliPay
from Qshop.settings import alipay_private_key_string,alipay_public_key_string
import logging
collect = logging.getLogger("django")

## 登录装饰器
def LoginVaild(func):
    ## 1. 获取cookie中username和email
    ## 2. 判断username和email
    ## 3. 如果成功  跳转
    ## 4. 如果失败   login.html
    def inner(request,*args,**kwargs):
        username = request.COOKIES.get('username')
        ## 获取session
        session_username = request.session.get("username")
        if username and session_username and username == session_username:
            return func(request,*args,**kwargs)
        else:
            return HttpResponseRedirect('/Buyer/login/')
    return inner
# Create your views here.
from django.views.decorators.cache import cache_page
## 首页
@cache_page(60*20)    ## 视图中使用缓存， 缓存寿命20分钟
def index(request):

    goods_type = GoodsType.objects.all()
    result = []
    for type in goods_type:
        goods = type.goods_set.order_by("-goods_price")
        if len(goods) >= 4:
            goods = goods[:4]
            result.append({"type":type,"goods":goods})
    ## 构建一个返回数据类型   返回满足4条的商品，有4条商品的类型
    return render(request,"buyer/index.html",locals())

def login(request):
    if request.method == "POST":
        error_msg = ""
        email = request.POST.get("email")
        password = request.POST.get("pwd")
        if email:
            user = LoginUser.objects.filter(email=email,user_type=1).first()
            if user:
                ## 存在
                if user.password == setPassword(password):
                    ## 登录成功
                    ## 跳转页面
                    # error_msg = "登录成功"
                    # return HttpResponseRedirect('/index/')
                    ## 设置cookie
                    response  = HttpResponseRedirect("/Buyer/index/")
                    response.set_cookie("username",user.username)
                    response.set_cookie("userid",user.id)
                    request.session['username'] = user.username  ## 设置session
                    collect.info("---------------%s is login-------------" % user.username)
                    return response
                else:
                    error_msg = "密码错误"
            else:
                error_msg = "用户不存在"
        else:
            error_msg = "邮箱不可以为空"

    return render(request,"buyer/login.html",locals())

def register(request):
    if request.method == "POST":
        error_msg = ""
        email = request.POST.get("email")
        password = request.POST.get("pwd")
        user_name = request.POST.get("user_name")
        if email:
            ## 判断邮箱是否存在
            loginuser = LoginUser.objects.filter(email=email).first()
            if not loginuser:
                ## 不存在 写库
                user = LoginUser()
                user.email = email
                user.username = user_name
                user.password = setPassword(password)
                user.save()
                return HttpResponseRedirect('/Buyer/login/')
            else:
                error_msg = "邮箱已经被注册，请登录"
        else:
            error_msg = "邮箱不可以为空"

    return render(request,"buyer/register.html")
## 登出
def logout(request):
    # 删除cookie   删除  session
    response = HttpResponseRedirect("/Buyer/login/")
    # response.delete_cookie("kename")
    keys = request.COOKIES.keys()
    for one in keys:
        response.delete_cookie(one)

    del request.session['username']
    return response

## 商品列表
def goods_list(request):
    """
    req_type    完成判断请求
        当 req_type = search
            keywords 商品的名字
        当 req_type = findall
            keywords传递的类型id，寻找该类型下面的商品
    :param request:
    :return:
    """
    keywords = request.GET.get("keywords")
    req_type = request.GET.get("req_type")
    if req_type == "findall":
        ##   查看更多
        goods_type = GoodsType.objects.get(id=keywords)
        goods = goods_type.goods_set.all()   ## 反向查询，
    elif req_type == "search":
        ### 搜索功能
        goods = Goods.objects.filter(goods_name__contains=keywords).all()
    else:
        goods = Goods.objects.all()
    ## 从 商品集中切片
    end = len(goods) // 5
    end += 1
    recommend = goods.order_by("-goods_pro_time")[:end]
    return render(request,"buyer/goods_list.html",locals())

def detail(request,id):
    goods = Goods.objects.get(id=int(id))
    return render(request,"buyer/detail.html",locals())

##个人中心
@LoginVaild
def user_center_info(request):
    return render(request,"buyer/user_center_info.html",locals())


import time
## 订单页面
@LoginVaild
def place_order(request):
    ## 保存订单
    goods_id = request.GET.get("goods_id")      # 商品id
    goods_count = request.GET.get("goods_count")   ## 订单数量
    user_id = request.COOKIES.get("userid")
    if goods_id and goods_count:
        goods_id = int(goods_id)
        goods_count = int(goods_count)
        goods = Goods.objects.get(id=goods_id)
        ## 保存订单表
        payorder = PayOrder()
        order_number = str(time.time()).replace('.','')     ## 生产订单编号
        payorder.order_number = order_number   ## 订单编号
        payorder.order_status = 0
        payorder.order_total = goods.goods_price * goods_count
        payorder.order_user = LoginUser.objects.get(id = user_id)
        payorder.save()
        ## 保存订单详情表
        orderinfo = OrderInfo()
        orderinfo.order_id = payorder
        orderinfo.goods = goods
        orderinfo.goods_count = goods_count
        orderinfo.goods_price = goods.goods_price
        orderinfo.goods_total_price = goods.goods_price * goods_count
        orderinfo.store_id = goods.goods_store
        orderinfo.save()


        total_count = 0
        all_goods_info = payorder.orderinfo_set.all()
        for one in all_goods_info:
            total_count += one.goods_count

    return render(request,"buyer/place_order.html",locals())



@LoginVaild
def place_order_more(request):
    data = request.GET
    userid = request.COOKIES.get("userid")
    #   {'count_11': ['1'], 'goods_13': ['on'], 'count_17': ['1'], 'goods_17': ['on'], 'count_13': ['1']}
    print (data)
    ## 区分   通过获取前端get请求的参数，找到goods_id 和对应的数量
    ## startwith  以goods开始的key
    data_item = data.items()
    request_data = []  ##   [(),(),()]
    for key,value in data_item:
        # print ("%s-------%s"%(key,value))     key : goods_商品id_购物车id
        if key.startswith("goods"):
            goods_id = key.split("_")[1]
            count = request.GET.get("count_"+goods_id)
            cart_id = key.split("_")[2]
            # print("%s ++++++++  %s" %(goods_id,count))
            request_data.append((int(goods_id),int(count),int(cart_id)))
    # print (request_data)
    if request_data:
        ## 保存数据
        ##   保存订单表   订单详情表
        ## 订单  保存一笔订单
        payorder = PayOrder()
        order_number = str(time.time()).replace('.','')     ## 生产订单编号
        payorder.order_number = order_number   ## 订单编号
        payorder.order_status = 0
        # payorder.order_total = 所有商品的小计之和
        payorder.order_total = 0
        payorder.order_user = LoginUser.objects.get(id = userid)
        payorder.save()
        order_total = 0
        total_count = 0  ## 商品总数量
        ## 订单详情   保存多条，一种商品一条数据
        for goods_id_one,count_one,cart_id in request_data:
            ## 遍历到一条订单中的多条商品的id 和对应的数量
            goods = Goods.objects.get(id =goods_id_one)
            orderinfo = OrderInfo()
            orderinfo.order_id = payorder
            orderinfo.goods = goods
            orderinfo.goods_count = count_one
            orderinfo.goods_price = goods.goods_price
            orderinfo.goods_total_price = goods.goods_price * count_one
            orderinfo.store_id = goods.goods_store
            orderinfo.save()
            order_total += goods.goods_price * count_one
            total_count += count_one

            cart = Cart.objects.get(id = cart_id)
            cart.order_number = order_number
            cart.save()


        payorder.order_total = order_total
        payorder.save()

    return render(request,"buyer/place_order.html",locals())








def AlipayViews(request):
    order_id = request.GET.get("order_id")    ## 订单id
    payorder = PayOrder.objects.get(id=order_id)
    ## 实例化支付对象
    alipay = AliPay(
        appid='2016101300673550',
        app_notify_url=None,
        app_private_key_string=alipay_private_key_string,
        alipay_public_key_string=alipay_public_key_string,
        sign_type="RSA2",
    )
    ## 实例化订单
    order_string = alipay.api_alipay_trade_page_pay(
        subject='天天生鲜',  ## 交易主题
        out_trade_no=payorder.order_number,  ## 订单号
        total_amount=str(payorder.order_total),  ## 交易总金额
        return_url="http://127.0.0.1:8000/Buyer/payresult/",  ##  请求支付，之后及时回调的一个接口
        notify_url="http://127.0.0.1:8000/Buyer/payresult/"  ##  通知地址，
    )
    ##   发送支付请求
    ## 请求地址  支付网关 + 实例化订单
    result = "https://openapi.alipaydev.com/gateway.do?" + order_string
    # print(result)

    return HttpResponseRedirect(result)

def payresult(request):

    ## 通过get获取支付宝传递参数，获取其中的订单号，修改订单的状态
    order_number = request.GET.get("out_trade_no")
    paryorder = PayOrder.objects.get(order_number=order_number)
    paryorder.order_status = 1    ## 修改订单状态
    ## 修改订单详情的状态
    ## 查询订单详情
    order_info = paryorder.orderinfo_set.all()
    for one in order_info:
        one.status = 1
        one.save()
    paryorder.save()
    return render(request,"buyer/payresult.html",locals())

## 添加购物车
@LoginVaild
def add_cart(request):
    """
    使用post请求，完成添加购物车功能
    :param request:  goods_id(商品id)    count(数量）
    :return:  json  code   msg
    """
    result = {"code":10001,"msg":""}
    if request.method == "POST":
        goods_id = request.POST.get("goods_id")
        count = float(request.POST.get("count",1))   ##  1 为默认值
        user_id = request.COOKIES.get("userid")

Qshop/Buyer/templates/buyer/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
    <script type="text/javascript" src="/static/buyer/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="/static/buyer/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/static/buyer/js/slide.js"></script>
    {% block style %}{% endblock %}
</head>
<body>
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到天天生鲜!</div>
        <div class="fr">
            <div class="login_btn fl">
                {% if request.COOKIES.username %}
                    <a href="#">欢迎{{ request.COOKIES.username }}</a>
                    <span>|</span>
                    <a href="/Buyer/logout/">退出</a>
                {% else %}
                    <a href="/Buyer/login/">登录</a>
                    <span>|</span>
                    <a href="/Buyer/register/">注册</a>

                {% endif %}

            </div>
            <div class="user_link fl">
                <span>|</span>
                <a href="/Buyer/user_center_info/">用户中心</a>
                <span>|</span>
                <a href="/Buyer/cart/">我的购物车</a>
                <span>|</span>
                <a href="user_center_order.html">我的订单</a>
            </div>
        </div>
    </div>
</div>

<div class="search_bar clearfix">
    <a href="/Buyer/index/" class="logo fl"><img src="/static/buyer/images/logo.png"></a>
    <div class="search_con fl">
        <input type="text" class="input_text fl" name="" placeholder="搜索商品" id = "keywords">
        <input type="button" class="input_btn fr" name="" value="搜索" onclick="getgoods()">
    </div>
    <div class="guest_cart fr">
        <a href="/Buyer/cart/" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count">1</div>
    </div>
</div>
{% block contnet %}
{% endblock %}

<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>
{% block script %}{% endblock %}
<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
<script>
    function getgoods() {
        keywords = $("#keywords").val();
        console.log(keywords);
        if (keywords){
            url = "/Buyer/goods_list/?keywords=" +keywords +"&req_type=search";
            //console.log(url);
            window.location.href=url;   //  js 当中跳转页面
        }
    }
</script>
<script type="text/javascript">
    BCSlideshow('focuspic');
    var oFruit = document.getElementById('fruit_more');
    var oShownum = document.getElementById('show_count');

    var hasorder = localStorage.getItem('order_finish');

    if (hasorder) {
        oShownum.innerHTML = '2';
    }

    oFruit.onclick = function () {
        window.location.href = 'list.html';
    }
</script>
</body>
</html>

Qshop/Buyer/templates/buyer/cart.html
{% extends "buyer/base.html" %}
{% block title %}
    购物车
{% endblock %}

{% block contnet %}
    	<div class="total_count">全部商品<em>{{ count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="/Buyer/place_order_more/">
    {% for cart_one in cart_list %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input class="goods_check" type="checkbox" name="goods_{{ cart_one.goods.id }}_{{ cart_one.id }}"></li>
		<li class="col02"><img src="/static/{{ cart_one.goods.picture }}"></li>
		<li class="col03">{{ cart_one.goods.goods_name }}<br><em>{{ cart_one.goods_price }}元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">{{ cart_one.goods_price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{ cart_one.goods_number }}" name="count_{{ cart_one.goods.id }}">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">{{ cart_one.goods_total }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" id = "boxall"></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em id="total_mount">0.0</em><br>共计<b id="total_num">0</b>件商品</li>
		<li class="col04"><input style="width: 100px;height: 50px;background-color: pink" type="submit" value="去结算"></li>
	</ul>

    </form>

{% endblock %}

{% block script %}
    <script>
    $("#boxall").click(
        function () {
            //console.log(1111);
            //console.log(this.checked);   //  得到this指向的对象有没有 checked属性
            // this.checked   返回  true 选中（有checked属性）   false  没有选中 没有checked属性
            // 当选中的时候，增加goods_check checked属性
            // 当不选中的时候，去掉goods_check 的 checked属性

            if(this.checked){
                //   当 条件为 true 的时候   全选
                $(".goods_check").prop("checked",true);
            }else{
                //  flase  全不选
                 $(".goods_check").prop("checked",false);
            }
            add();
        }
    )

    $(".goods_check").each(
        function () {
            // console.log(222222)
            $(this).click(
                function () {
                if(!this.checked){
                       // $("#boxall").prop("checked",true)
                    $("#boxall").prop("checked",false)
                    }
                    add();
                }
            )

        }
    )

    function add() {
        //  完成方法
        //  获取选中的商品的 数量 和 小计
        //   计算出 商品的总数量和 总价
        //  给元素 赋值
        var dic = {num:0,total:0}
        $(".goods_check").each(function () {
            // 拿到循环的每一条，判断是否有 checked 属性，获取有checked属性的小计和数量
            if(this.checked){
                //  被选中的
                //  数量
                var num = parseInt($(this).parents(".cart_list_td").find(".num_show").val());
{#                console.log(num);#}
                // 小计   col07
                var total = parseFloat($(this).parents(".cart_list_td").find(".col07").text());
{#                console.log(total)#}
                // 计算   计算总价   总数量
                dic.num += num
                dic.total += total
            }
        })
{#        console.log(dic)#}
        // 赋值
        $("#total_mount").text(dic.total)
        $("#total_num").text(dic.num)
    }

    </script>
{% endblock %}

Qshop/Buyer/templates/buyer/goods_list.html
{% extends "buyer/base.html" %}
{% block title%}
    商品列表
{% endblock %}
{% block contnet %}
    	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>
    {% if goods%}
	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for one in recommend %}
					<li>
						<a href="#"><img src="/static/{{ one.picture }}"></a>
						<h4><a href="#">{{ one.goods_name }}</a></h4>
						<div class="prize">￥{{ one.goods_price }}</div>
					</li>
                       {% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for goods in goods %}
				<li>
					<a href="/Buyer/detail/{{ goods.id }}"><img src="/static/{{ goods.picture }}"></a>
					<h4><a href="/Buyer/detail/{{ goods.id }}">{{ goods.goods_name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goods.goods_price }}</span>
						<span class="unit">16.80/500g</span>
						<a id="{{ goods.id }}" href="#" class="add_goods" title="加入购物车" onclick="add_cart(this)"></a>
					</div>
				</li>
                {% endfor %}

			</ul>

			<div class="pagenation">
				<a href="#"><上一页</a>
				<a href="#" class="active">1</a>
				<a href="#">2</a>
				<a href="#">3</a>
				<a href="#">4</a>
				<a href="#">5</a>
				<a href="#">下一页></a>
			</div>
		</div>
	</div>
        {% else %}
        <p style="text-align: center;font-size: 20px;">
            抱歉，我们暂时没有该商品，请期待。。。 <br>
            您可以查询一下
            <a href="/Buyer/goods_list/?keywords=3&req_type=findall">肉肉</a>
        </p>
    {% endif %}


{% endblock %}


{% block script %}
    <script>

    function add_cart(obj) {
        var goods_id = obj.id;
        console.log(goods_id);
        url = "/Buyer/add_cart/"
        send_data = {
            "goods_id":goods_id,
            "csrfmiddlewaretoken":'{{ csrf_token }}'
        }
        $.ajax(
            {
                url:url,
                type:"post",
                data:send_data,
                success:function (data) {
                    console.log(data);
                    alert(data["msg"]);

                },
                error:function (error) {
                    console.log(error)
                }
            }
        )
    }
    </script>
{% endblock %}

Qshop/Buyer/templates/buyer/payresult.html
{% extends "buyer/base.html"%}
{% block title %}
    支付结果
{% endblock %}

{% block contnet %}
    <div class="list_model">
        <h1>支付结果</h1>
    <table>
            {% for k,v in request.GET.items %}
                <tr>
                <th>{{ k }}:</th>
                <td>
                    {{ v }}
                </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

Qshop/Buyer/templates/buyer/user_center_order.html
{% extends "buyer/base.html" %}
{% block title %}
    全部订单
{% endblock %}

{% block contnet %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/Buyer/user_center_info/">· 个人信息</a></li>
				<li><a href="/Buyer/user_center_order/" class="active">· 全部订单</a></li>
				<li><a href="user_center_site.html">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>

                {% for one in paryorder %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ one.order_date | date:"Y-m-d" }}</li>
					<li class="col02">订单号：{{ one.order_number }}</li>
					<li class="col02 stress">{{ one.get_order_status_display }}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order_info in one.orderinfo_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{ order_info.goods.picture }}"></li>
									<li class="col02">{{ order_info.goods.goods_name }}<em>{{ order_info.goods_price }}元/500g</em></li>
									<li class="col03">{{ order_info.goods_count }}</li>
									<li class="col04">{{ order_info.goods_total_price }}元</li>
								</ul>
                                {% endfor %}

							</td>
							<td width="15%">{{ one.order_total }}元</td>
							<td width="15%">{{ one.get_order_status_display }}</td>

                        {% if one.order_status == 0 %}
							<td width="15%"><a href="/Buyer/alipayviews/?order_id={{ one.id }}" class="oper_btn">去付款</a></td>
                        {% else %}
                            <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                        {% endif %}

						</tr>
					</tbody>
				</table>
            {% endfor %}



				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock %}